services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - order-service-data:/var/lib/postgresql/data
    networks:
      - e_com_network

  order-service:
    build: .
    ports:
      - '${ORDER_SERVICE_PORT}:${ORDER_SERVICE_PORT}'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NATS_URL=${NATS_URL}
      - PORT=${ORDER_SERVICE_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - ORDER_SERVICE_PORT=${ORDER_SERVICE_PORT}
      - NATS_PORT=${NATS_PORT}
    depends_on:
      - postgres
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - e_com_network

volumes:
  order-service-data:

networks:
  e_com_network:
    external: true
